Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10 ===== == == == == == == == == == == Input 10 20 30 40 50 60 70 80 90 100 y1 25 = (10+20+30+40)/4 y2 35 = (20+30+40+50)/4 y3 45 = (30+40+50+60)/4 y4 55 = (40+50+60+70)/4 y5 65 = (50+60+70+80)/4 y6 75 = (60+70+80+90)/4 y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [ ]:
import pandas as pd
import numpy as np 

def sequence(new_arr,num1):
    u= new_arr.size-num1+1
    matrix = np.array([new_arr[i+j] for i in range(u) for j in range(num1)]).reshape(u,num1)
    output = np.sum(matrix,axis = 1,keepdims=True)/num1
    for a,b in zip(matrix,output):
        print(a,b)

In [12]:
new_arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
num1 = 10

In [14]:
sequence(new_arr,num1)

[ 3  5  7  2  8 10 11 65 72 81] [26.4]
[ 5  7  2  8 10 11 65 72 81 99] [36.]
[  7   2   8  10  11  65  72  81  99 100] [45.5]
[  2   8  10  11  65  72  81  99 100 150] [59.8]


Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1

In [16]:
def powerarray(arr,num,increase=False):
    if increase:
        output_matrix = np.array([i**j for i in arr for j in range(num)]).reshape(arr.size,num)     
    
    elif not increase :
         output_matrix = np.array([i**(num-j-1) for i in arr for j in range(num) ]).reshape(arr.size,num)
             
    return output_matrix

In [17]:
arr=np.array([1,2,3,4,5,6,7,8])
num = 3
powerarray(arr,num,True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25],
       [ 1,  6, 36],
       [ 1,  7, 49],
       [ 1,  8, 64]])

In [18]:
arr = np.array([1,2,3,4])
num = 3
powerarray(arr,num,False) 

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])